# Generated by Django 6.1.1 on 2026-09-12 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(db_index=True, max_length=32, unique=True)),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(db_index=True, max_length=100)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_index=True, default='media', max_length=20)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_gestion', 'En gestión'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], db_index=True, default='recibida', max_length=20)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('presencial', 'Presencial')], default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pqrs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('identificacion', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solicitantes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo_accion', models.CharField(choices=[('comentario', 'Comentario'), ('cambio_estado', 'Cambio de estado'), ('cambio_prioridad', 'Cambio de prioridad'), ('asignacion', 'Asignación'), ('sistema', 'Sistema')], default='comentario', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('pqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='pqr.pqr')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seguimientos',
                'ordering': ['fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='pqr',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pqrs', to='pqr.solicitante'),
        ),
        migrations.AddIndex(
            model_name='pqr',
            index=models.Index(fields=['tipo', 'estado'], name='pqrs_tipo_d6edd9_idx'),
        ),
        migrations.AddIndex(
            model_name='pqr',
            index=models.Index(fields=['prioridad', 'estado'], name='pqrs_priorid_5dddb7_idx'),
        ),
        migrations.AddIndex(
            model_name='pqr',
            index=models.Index(fields=['categoria', 'estado'], name='pqrs_categor_36a469_idx'),
        ),
    ]
